# Meraki and TopDesk Details

MERAKI_API_KEY = 'Your API Key'
MERAKI_ORGANIZATION_ID = 'Your Organization ID'

TOPDESK_USERNAME = 'Your Username'
TOPDESK_PASSWORD = 'Your App Password'
TOPDESK_URL = 'http://localhost/tas/api/incidents'
TOPDESK_CALLER_ID = '127ab07d-87cd-5db6-b3ae-ae1f45cfefa6'
TOPDEK_CALLTYPE_NAME = '9 - Monitoring - Alert'
TOPDEK_ENTRYTYPE_NAME = '9 - Monitoring - Alert'

TOPDESK_AP_CATEGORY_NAME = 'Netzwerk'
TOPDESK_AP_SUBCATEGORY_NAME = 'WLAN Filialen Meraki'
TOPDESK_NETWORK_CATEGORY_NAME = 'Netzwerk'
TOPDESK_NETWORK_SUBCATEGORY_NAME = 'Firewall Meraki'
TOPDESK_SETTINGS_CATEGORY_NAME = 'Netzwerk'
TOPDESK_SETTINGS_SUBCATEGORY_NAME = 'LAN Filialen Meraki'
TOPDESK_VPN_CATEGORY_NAME = 'Netzwerk'
TOPDESK_VPN_SUBCATEGORY_NAME = 'VPN'
TOPDESK_GENERAL_CATEGORY_NAME = 'Netzwerk'

